### ISSUE TITLE
Exception when subscribing to sleep data

### ISSUE THREAD

**Issue by pujjwal** [android/location-samples#272]
I am trying to subscribe to user sleep data by going through the documentation - https://developers.google.com/location-context/sleep
But I am getting an exception -

**Exception when subscribing to sleep data: java.lang.SecurityException: App should be whitelisted for Sleep Segment API** 
W/System.err: java.lang.SecurityException: App should be whitelisted for Sleep Segment API - android.assignment.framework
W/System.err:     at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
W/System.err:     at android.os.Parcel.createException(Parcel.java:2357)
W/System.err:     at android.os.Parcel.readException(Parcel.java:2340)
W/System.err:     at android.os.Parcel.readException(Parcel.java:2282)
W/System.err:     at com.google.android.gms.internal.location.zza.zzx(com.google.android.gms:play-services-location@@18.0.0:3)
W/System.err:     at com.google.android.gms.internal.location.zzal.zzv(com.google.android.gms:play-services-location@@18.0.0:5)
W/System.err:     at com.google.android.gms.location.zzd.accept(com.google.android.gms:play-services-location@@18.0.0:3)
W/System.err:     at com.google.android.gms.common.api.internal.zacj.doExecute(com.google.android.gms:play-services-base@@17.5.0:2)
W/System.err:     at com.google.android.gms.common.api.internal.zah.zaa(com.google.android.gms:play-services-base@@17.5.0:9)
W/System.err:     at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zac(com.google.android.gms:play-services-base@@17.5.0:193)
W/System.err:     at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zab(com.google.android.gms:play-services-base@@17.5.0:158)
W/System.err:     at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zap(com.google.android.gms:play-services-base@@17.5.0:120)
W/System.err:     at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zao(com.google.android.gms:play-services-base@@17.5.0:38)
W/System.err:     at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.onConnected(com.google.android.gms:play-services-base@@17.5.0:17)
W/System.err:     at com.google.android.gms.common.internal.zag.onConnected(com.google.android.gms:play-services-base@@17.5.0:2)
W/System.err:     at com.google.android.gms.common.internal.BaseGmsClient$zzf.zza(com.google.android.gms:play-services-basement@@17.5.0:24)
W/System.err:     at com.google.android.gms.common.internal.BaseGmsClient$zza.zza(com.google.android.gms:play-services-basement@@17.5.0:12)
W/System.err:     at com.google.android.gms.common.internal.BaseGmsClient$zzc.zzc(com.google.android.gms:play-services-basement@@17.5.0:11)
W/System.err:     at com.google.android.gms.common.internal.BaseGmsClient$zzb.handleMessage(com.google.android.gms:play-services-basement@@17.5.0:49)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:67)

**What whitelisting the error message talking about here ? 
What to whitelist and where ? Any pointer to documentation would be helpful.**

Below line is already present in android manifest

```
<uses-permission android:name="com.google.android.gms.permission.ACTIVITY_RECOGNITION" />
```

**Comment by blueberry404** [comment]
In order to remove the exception, I had to declare **minSDKVersion** to **29** in **build.gradle**

In manifest, write:
`<uses-permission android:name="android.permission.ACTIVITY_RECOGNITION" />`

instead of:
`<uses-permission android:name="com.google.android.gms.permission.ACTIVITY_RECOGNITION" />`

You would also need to grant runtime permission for **Manifest.permission.ACTIVITY_RECOGNITION**. I hope they mention this somewhere in the documentation.

**Comment by pujjwal** [comment]
It was something related to device, same code deployed on Samsung phone was working, but not on my MiA3
The  runtime Activity permissions were granted.
