### ISSUE TITLE
Location Updates in the Background no updates are receiving in LocationUpdatesBroadcastReceiver

### ISSUE THREAD

**Issue by usmanhashmi2123** [android/location-samples#312]
I have run LocationUpdatesBroadcastReceiver sample on android 12.
But not received a single location in LocationUpdatesBroadcastReceiver.

updates started and stoped successfully but received no locations data in receiver.

All Location permissions are given

**Comment by Sexroom2022** [comment]
@usmanhashmi2123

**Comment by usmanhashmi2123** [comment]
it worked when i 

changed

PendingIntent.getBroadcast(context,32,intent,PendingIntent.FLAG_IMMUTABLE or PendingIntent.FLAG_UPDATE_CURRENT)

to

PendingIntent.getBroadcast(context,32,intent,PendingIntent.FLAG_MUTABLE or PendingIntent.FLAG_UPDATE_CURRENT)
