### ISSUE TITLE
Location always null

### ISSUE THREAD

**Issue by Enorio** [android/location-samples#65]
I didnt see any issue with my problem, but this app always shows me that i dont have location enable, even when i have. I tried google maps and it did work, but in this, it doesnt. 

I didnt change any code

**Comment by 786lokesh** [comment]
In which android version you were checking ?

**Comment by Enorio** [comment]
v 4.4.2

**Comment by 786lokesh** [comment]
Do these:
1). Check what is the minSdk set in your android manifest file.
2). Use run time permissions for new version of android.
3). Make sure location settings are prompt to user if the settings doesn't satisfy.
If these didn't work can you paste you log cat here ?

**Comment by Enorio** [comment]
I didn't change any code, thus the manifest doesn't have anything about sdk.

I works when i put the run time permissions. Thank you.

**Comment by 786lokesh** [comment]
You should always update your gradle when you are opening another project in Android Studio from different source. Good luck.

**Comment by anil1kumar** [comment]
I am getting location as null always.
I am running on 7.0
problem : when I granted permission at runtime **my location** is not **turning on** in my device but   if I enable it manually, problem is solved
can anyone help me? Thank you.

**Comment by 786lokesh** [comment]
share your function which is turning on location else post it on StackOverflow.

**Comment by anil1kumar** [comment]
I just copied the MainActivity class of Basiclocationsample from the above code.

**Comment by Enorio** [comment]
My problem was that i didn't had a SIM card in the phone. After i inserted a SIM card, the location appeared.
